### PR TITLE
Update avpop_mono defaults

### PR DESCRIPTION
**Pull request by gbeltzmo**
@aphearin I thought the updated params looked good, but I pulled the changes and made some diagnostic plots and realized the parameters needed to be modified further. This should do it, but you should take a look before I merge.

### CODE REVIEW

**Comment by aphearin** [comment]
This code change confused me, because in #65 I thought I set these parameter values so that `Av=0.1` for all galaxies. But I guess that's not true? The reason I thought that was because I thought the meaning of the parameters I changed controlled the value of `suav`, where `Av = jax.nn.softplus(suav)`. And so when I set the parameter values to all equal `-2.25`, I thought I was setting `Av=0.1=jax.nn.softplus(-2.25)`. But it looks like I must have gotten turned around. Maybe what these parameters actually control is the value of an unbounded parameter?

**Comment by aphearin** [comment]
@gbeltzmo I think I see what happened. In f53ed7bb38852f51732e0b10c776f99c13c350a6 I fixed what I think was the actual bug.

> but I pulled the changes and made some diagnostic plots and realized the parameters needed to be modified further. 

Could you use repeat the diagnostic plot checks you did using this new code?

**Comment by gbeltzmo** [comment]
@aphearin can do!

**Review by aphearin — APPROVED** [review]
Now that `AVPOP_PBOUNDS_PDICT` has been corrected so that the `ylo` and `yhi` params are bounded by `SUAV_BOUNDS` rather than a random `U_BOUNDS` that was leftover from legacy code, I think this is good to go.

No wonder we were having so much trouble fitting our dust model - this was a bug leading to very crazy default levels of attenuation.

**Pull request merged**
