### PR TITLE
Update defaults to AvPop so that Av=0.1 for all galaxies

### PR DESCRIPTION
**Pull request by aphearin**
Update defaults to AvPop so that Av=0.1 for all galaxies - @gbeltzmo let's use this PR to update the Av defaults.

### CODE REVIEW

**Comment by aphearin** [comment]
I will leave this open for @gbeltzmo to possibly revise further, and to merge when ready.

**Comment by gbeltzmo** [comment]
I think this looks good!

**Comment by gbeltzmo** [comment]
But I don't think I have permission to merge this PR.

**Comment by aphearin** [comment]
Ok I went ahead and merged myself then, but @gbeltzmo you should now have appropriate permissions to merge Diffsky PRs yourself.

**Comment by aphearin** [comment]
@AlanPearl since you are using diffsky as a trial problem for your fitters, be sure to update your code to include this PR, since this change to the defaults has a very large effect on the gradient descent.

**Pull request merged**
